"""init tables

Revision ID: ca6343f43e5c
Revises: 
Create Date: 2026-02-10 20:27:36.965713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6343f43e5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['current_version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('indicator_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_date', sa.Date(), nullable=False),
    sa.Column('unit', sa.String(length=120), nullable=False),
    sa.Column('shift', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('censo_dia', sa.Integer(), nullable=True),
    sa.Column('admissoes', sa.Integer(), nullable=True),
    sa.Column('altas_transferencias', sa.Integer(), nullable=True),
    sa.Column('obitos', sa.Integer(), nullable=True),
    sa.Column('quedas_paciente', sa.Integer(), nullable=True),
    sa.Column('extubacao_acidental', sa.Integer(), nullable=True),
    sa.Column('novas_lpp', sa.Integer(), nullable=True),
    sa.Column('erros_medicacao', sa.Integer(), nullable=True),
    sa.Column('broncoaspiracao', sa.Integer(), nullable=True),
    sa.Column('parada_cardio', sa.Integer(), nullable=True),
    sa.Column('reinternacao_24h', sa.Integer(), nullable=True),
    sa.Column('faltas_tecnicos', sa.Integer(), nullable=True),
    sa.Column('atestados_equipe', sa.Integer(), nullable=True),
    sa.Column('horas_extras_geradas', sa.Float(), nullable=True),
    sa.Column('manutencao_equipamento', sa.Boolean(), nullable=True),
    sa.Column('falta_insumo_critico', sa.Boolean(), nullable=True),
    sa.Column('exames_pendentes', sa.Integer(), nullable=True),
    sa.Column('conclusao_prontuarios', sa.Boolean(), nullable=True),
    sa.Column('conflitos_acompanhantes', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_date', 'unit', 'shift', name='uq_indicator_daily_ref_unit_shift')
    )
    with op.batch_alter_table('indicator_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicator_daily_ref_date'), ['ref_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_daily_shift'), ['shift'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicator_daily_unit'), ['unit'], unique=False)

    op.create_table('sectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectors_name'), ['name'], unique=True)

    op.create_table('sick_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=32), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('turno', sa.String(length=20), nullable=True),
    sa.Column('data_atestado', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('cid', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_login', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('force_password_change', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(), nullable=True),
    sa.Column('matricula', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_sector_id'), ['sector_id'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'user_id', name='uq_doc_user_read')
    )
    with op.batch_alter_table('document_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_reads_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_reads_user_id'), ['user_id'], unique=False)

    op.create_table('nursing_daily_override',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('shift', sa.String(length=5), nullable=True),
    sa.Column('is_coop', sa.Boolean(), nullable=True),
    sa.Column('coop_name', sa.String(length=150), nullable=True),
    sa.Column('coop_coren', sa.String(length=50), nullable=True),
    sa.Column('coop_role', sa.String(length=50), nullable=True),
    sa.Column('related_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_monthly_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('servico', sa.String(length=80), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scales_ano'), ['ano'], unique=False)
        batch_op.create_index(batch_op.f('ix_scales_mes'), ['mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_scales_status'), ['status'], unique=False)

    op.create_table('shift_swaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('substitute_id', sa.Integer(), nullable=False),
    sa.Column('original_date', sa.Date(), nullable=False),
    sa.Column('original_shift', sa.String(length=5), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('target_shift', sa.String(length=5), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('refusal_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['substitute_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_monthly_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['nursing_monthly_schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nursing_monthly_cell',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('planned_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('shift', sa.String(length=10), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['nursing_monthly_member.id'], ),
    sa.ForeignKeyConstraint(['planned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['nursing_monthly_schedule.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nursing_monthly_cell')
    op.drop_table('nursing_monthly_member')
    op.drop_table('announcement_reads')
    op.drop_table('shift_swaps')
    with op.batch_alter_table('scales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scales_status'))
        batch_op.drop_index(batch_op.f('ix_scales_mes'))
        batch_op.drop_index(batch_op.f('ix_scales_ano'))

    op.drop_table('scales')
    op.drop_table('nursing_monthly_schedule')
    op.drop_table('nursing_daily_override')
    with op.batch_alter_table('document_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_document_reads_document_id'))

    op.drop_table('document_reads')
    op.drop_table('announcements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_sector_id'))
        batch_op.drop_index(batch_op.f('ix_users_matricula'))

    op.drop_table('users')
    op.drop_table('sick_notes')
    with op.batch_alter_table('sectors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectors_name'))

    op.drop_table('sectors')
    with op.batch_alter_table('indicator_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicator_daily_unit'))
        batch_op.drop_index(batch_op.f('ix_indicator_daily_shift'))
        batch_op.drop_index(batch_op.f('ix_indicator_daily_ref_date'))

    op.drop_table('indicator_daily')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))

    op.drop_table('documents')
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_document_id'))

    op.drop_table('document_versions')
    # ### end Alembic commands ###
